// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package config

// Config is the app-level configuration contract. The Go type is
// generated from this definition (see cue_types_gen.go), koanf
// decodes local.yaml into it, and mizucue validates the result —
// one source of truth for shape, defaults, and constraints.
type Config struct {
	// env is the deployment environment.
	Env string `json:"env"`

	// port is the HTTP listen address.
	Port string `json:"port"`

	// level is the minimum slog level name.
	Level string `json:"level"`
}
