// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: app_foo/file/v1/file.proto

package filev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scenario int32

const (
	Scenario_SCENARIO_UNSPECIFIED Scenario = 0
	Scenario_SCENARIO_GATEWAY     Scenario = 1
	Scenario_SCENARIO_CDN         Scenario = 2
)

// Enum value maps for Scenario.
var (
	Scenario_name = map[int32]string{
		0: "SCENARIO_UNSPECIFIED",
		1: "SCENARIO_GATEWAY",
		2: "SCENARIO_CDN",
	}
	Scenario_value = map[string]int32{
		"SCENARIO_UNSPECIFIED": 0,
		"SCENARIO_GATEWAY":     1,
		"SCENARIO_CDN":         2,
	}
)

func (x Scenario) Enum() *Scenario {
	p := new(Scenario)
	*p = x
	return p
}

func (x Scenario) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scenario) Descriptor() protoreflect.EnumDescriptor {
	return file_app_foo_file_v1_file_proto_enumTypes[0].Descriptor()
}

func (Scenario) Type() protoreflect.EnumType {
	return &file_app_foo_file_v1_file_proto_enumTypes[0]
}

func (x Scenario) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scenario.Descriptor instead.
func (Scenario) EnumDescriptor() ([]byte, []int) {
	return file_app_foo_file_v1_file_proto_rawDescGZIP(), []int{0}
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_app_foo_file_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_foo_file_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_app_foo_file_v1_file_proto_rawDescGZIP(), []int{0}
}

func (x *GetFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_app_foo_file_v1_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_foo_file_v1_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_app_foo_file_v1_file_proto_rawDescGZIP(), []int{1}
}

func (x *GetFileResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Form          *httpbody.HttpBody     `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	Scenario      Scenario               `protobuf:"varint,2,opt,name=scenario,proto3,enum=app_foo.file.v1.Scenario" json:"scenario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_app_foo_file_v1_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_foo_file_v1_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_app_foo_file_v1_file_proto_rawDescGZIP(), []int{2}
}

func (x *UploadFileRequest) GetForm() *httpbody.HttpBody {
	if x != nil {
		return x.Form
	}
	return nil
}

func (x *UploadFileRequest) GetScenario() Scenario {
	if x != nil {
		return x.Scenario
	}
	return Scenario_SCENARIO_UNSPECIFIED
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_app_foo_file_v1_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_foo_file_v1_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_app_foo_file_v1_file_proto_rawDescGZIP(), []int{3}
}

func (x *UploadFileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadFileResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_app_foo_file_v1_file_proto protoreflect.FileDescriptor

const file_app_foo_file_v1_file_proto_rawDesc = "" +
	"\n" +
	"\x1aapp_foo/file/v1/file.proto\x12\x0fapp_foo.file.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/httpbody.proto\" \n" +
	"\x0eGetFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x0fGetFileResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"t\n" +
	"\x11UploadFileRequest\x12(\n" +
	"\x04form\x18\x01 \x01(\v2\x14.google.api.HttpBodyR\x04form\x125\n" +
	"\bscenario\x18\x02 \x01(\x0e2\x19.app_foo.file.v1.ScenarioR\bscenario\"6\n" +
	"\x12UploadFileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url*L\n" +
	"\bScenario\x12\x18\n" +
	"\x14SCENARIO_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SCENARIO_GATEWAY\x10\x01\x12\x10\n" +
	"\fSCENARIO_CDN\x10\x022\xd0\x01\n" +
	"\vFileService\x12L\n" +
	"\aGetFile\x12\x1f.app_foo.file.v1.GetFileRequest\x1a .app_foo.file.v1.GetFileResponse\x12s\n" +
	"\n" +
	"UploadFile\x12\".app_foo.file.v1.UploadFileRequest\x1a#.app_foo.file.v1.UploadFileResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x04form\"\f/file:upload(\x01B\xa8\x01\n" +
	"\x13com.app_foo.file.v1B\tFileProtoP\x01Z,mizu.example/protogen/app_foo/file/v1;filev1\xa2\x02\x03AFX\xaa\x02\x0eAppFoo.File.V1\xca\x02\x0eAppFoo\\File\\V1\xe2\x02\x1aAppFoo\\File\\V1\\GPBMetadata\xea\x02\x10AppFoo::File::V1b\x06proto3"

var (
	file_app_foo_file_v1_file_proto_rawDescOnce sync.Once
	file_app_foo_file_v1_file_proto_rawDescData []byte
)

func file_app_foo_file_v1_file_proto_rawDescGZIP() []byte {
	file_app_foo_file_v1_file_proto_rawDescOnce.Do(func() {
		file_app_foo_file_v1_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_foo_file_v1_file_proto_rawDesc), len(file_app_foo_file_v1_file_proto_rawDesc)))
	})
	return file_app_foo_file_v1_file_proto_rawDescData
}

var file_app_foo_file_v1_file_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_foo_file_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_app_foo_file_v1_file_proto_goTypes = []any{
	(Scenario)(0),              // 0: app_foo.file.v1.Scenario
	(*GetFileRequest)(nil),     // 1: app_foo.file.v1.GetFileRequest
	(*GetFileResponse)(nil),    // 2: app_foo.file.v1.GetFileResponse
	(*UploadFileRequest)(nil),  // 3: app_foo.file.v1.UploadFileRequest
	(*UploadFileResponse)(nil), // 4: app_foo.file.v1.UploadFileResponse
	(*httpbody.HttpBody)(nil),  // 5: google.api.HttpBody
}
var file_app_foo_file_v1_file_proto_depIdxs = []int32{
	5, // 0: app_foo.file.v1.UploadFileRequest.form:type_name -> google.api.HttpBody
	0, // 1: app_foo.file.v1.UploadFileRequest.scenario:type_name -> app_foo.file.v1.Scenario
	1, // 2: app_foo.file.v1.FileService.GetFile:input_type -> app_foo.file.v1.GetFileRequest
	3, // 3: app_foo.file.v1.FileService.UploadFile:input_type -> app_foo.file.v1.UploadFileRequest
	2, // 4: app_foo.file.v1.FileService.GetFile:output_type -> app_foo.file.v1.GetFileResponse
	4, // 5: app_foo.file.v1.FileService.UploadFile:output_type -> app_foo.file.v1.UploadFileResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_foo_file_v1_file_proto_init() }
func file_app_foo_file_v1_file_proto_init() {
	if File_app_foo_file_v1_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_foo_file_v1_file_proto_rawDesc), len(file_app_foo_file_v1_file_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_foo_file_v1_file_proto_goTypes,
		DependencyIndexes: file_app_foo_file_v1_file_proto_depIdxs,
		EnumInfos:         file_app_foo_file_v1_file_proto_enumTypes,
		MessageInfos:      file_app_foo_file_v1_file_proto_msgTypes,
	}.Build()
	File_app_foo_file_v1_file_proto = out.File
	file_app_foo_file_v1_file_proto_goTypes = nil
	file_app_foo_file_v1_file_proto_depIdxs = nil
}
