// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package oaisvc

// ScrapeRequest is the input of GET /oai/scrape: one mandatory
// header.
type ScrapeRequest struct {
	Header struct {
		// key is the magic word echoed back.
		Key string `json:"key"`
	} `json:"header"`
}

// ScrapeResponse echoes the magic word back.
type ScrapeResponse struct {
	// message is the greeting.
	Message string `json:"message"`
}

// CreateOrderRequest is the input of POST /oai/user/{user_id}/order:
// one group per request location.
type CreateOrderRequest struct {
	Path struct {
		// user_id identifies the ordering user.
		UserId string `json:"user_id"`
	} `json:"path"`

	Query struct {
		// timestamp is the client's unix-second order time.
		UnixTime int64 `json:"timestamp,omitempty"`
	} `json:"query"`

	Header struct {
		// X-Region tells where the order is from.
		Region string `json:"X-Region,omitempty"`
	} `json:"header"`

	Body struct {
		// id is the client-supplied order id.
		Id string `json:"id"`

		// amount is the order amount and must be positive.
		Amount int64 `json:"amount"`

		// comment is optional free text.
		Comment string `json:"comment,omitempty"`
	} `json:"body"`
}

// CreateOrderResponse echoes the processed amount.
type CreateOrderResponse struct {
	// amount is the amount actually processed.
	Amount int64 `json:"amount"`
}

// DownloadPackageOperation is the OpenAPI contract of GET
// /oai/package — a raw gzip stream that reflection cannot describe.
// The members are @go(-) so the generated Go type stays empty; the
// definition name still keys the fragment for Schema.Operation,
// which mizuoai merges over the reflected operation with
// WithOperationPatch.
type DownloadPackageOperation struct {
	Responses struct {
	} `json:"responses"`
}
