// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: fooapp/namaste/v1/namaste.proto

package namastev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NamasteService_Namaste_FullMethodName = "/fooapp.namaste.v1.NamasteService/Namaste"
)

// NamasteServiceClient is the client API for NamasteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NamasteServiceClient interface {
	Namaste(ctx context.Context, in *NamasteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NamasteResponse], error)
}

type namasteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNamasteServiceClient(cc grpc.ClientConnInterface) NamasteServiceClient {
	return &namasteServiceClient{cc}
}

func (c *namasteServiceClient) Namaste(ctx context.Context, in *NamasteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NamasteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NamasteService_ServiceDesc.Streams[0], NamasteService_Namaste_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NamasteRequest, NamasteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NamasteService_NamasteClient = grpc.ServerStreamingClient[NamasteResponse]

// NamasteServiceServer is the server API for NamasteService service.
// All implementations must embed UnimplementedNamasteServiceServer
// for forward compatibility.
type NamasteServiceServer interface {
	Namaste(*NamasteRequest, grpc.ServerStreamingServer[NamasteResponse]) error
	mustEmbedUnimplementedNamasteServiceServer()
}

// UnimplementedNamasteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNamasteServiceServer struct{}

func (UnimplementedNamasteServiceServer) Namaste(*NamasteRequest, grpc.ServerStreamingServer[NamasteResponse]) error {
	return status.Error(codes.Unimplemented, "method Namaste not implemented")
}
func (UnimplementedNamasteServiceServer) mustEmbedUnimplementedNamasteServiceServer() {}
func (UnimplementedNamasteServiceServer) testEmbeddedByValue()                        {}

// UnsafeNamasteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NamasteServiceServer will
// result in compilation errors.
type UnsafeNamasteServiceServer interface {
	mustEmbedUnimplementedNamasteServiceServer()
}

func RegisterNamasteServiceServer(s grpc.ServiceRegistrar, srv NamasteServiceServer) {
	// If the following call panics, it indicates UnimplementedNamasteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NamasteService_ServiceDesc, srv)
}

func _NamasteService_Namaste_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NamasteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NamasteServiceServer).Namaste(m, &grpc.GenericServerStream[NamasteRequest, NamasteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NamasteService_NamasteServer = grpc.ServerStreamingServer[NamasteResponse]

// NamasteService_ServiceDesc is the grpc.ServiceDesc for NamasteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NamasteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fooapp.namaste.v1.NamasteService",
	HandlerType: (*NamasteServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Namaste",
			Handler:       _NamasteService_Namaste_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fooapp/namaste/v1/namaste.proto",
}
