// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: fooapp/namaste/v1/namaste.proto

package namastev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Namaste struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namaste) Reset() {
	*x = Namaste{}
	mi := &file_fooapp_namaste_v1_namaste_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namaste) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namaste) ProtoMessage() {}

func (x *Namaste) ProtoReflect() protoreflect.Message {
	mi := &file_fooapp_namaste_v1_namaste_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namaste.ProtoReflect.Descriptor instead.
func (*Namaste) Descriptor() ([]byte, []int) {
	return file_fooapp_namaste_v1_namaste_proto_rawDescGZIP(), []int{0}
}

func (x *Namaste) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NamasteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamasteRequest) Reset() {
	*x = NamasteRequest{}
	mi := &file_fooapp_namaste_v1_namaste_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamasteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamasteRequest) ProtoMessage() {}

func (x *NamasteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fooapp_namaste_v1_namaste_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamasteRequest.ProtoReflect.Descriptor instead.
func (*NamasteRequest) Descriptor() ([]byte, []int) {
	return file_fooapp_namaste_v1_namaste_proto_rawDescGZIP(), []int{1}
}

func (x *NamasteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NamasteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamasteResponse) Reset() {
	*x = NamasteResponse{}
	mi := &file_fooapp_namaste_v1_namaste_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamasteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamasteResponse) ProtoMessage() {}

func (x *NamasteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fooapp_namaste_v1_namaste_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamasteResponse.ProtoReflect.Descriptor instead.
func (*NamasteResponse) Descriptor() ([]byte, []int) {
	return file_fooapp_namaste_v1_namaste_proto_rawDescGZIP(), []int{2}
}

func (x *NamasteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_fooapp_namaste_v1_namaste_proto protoreflect.FileDescriptor

const file_fooapp_namaste_v1_namaste_proto_rawDesc = "" +
	"\n" +
	"\x1ffooapp/namaste/v1/namaste.proto\x12\x11fooapp.namaste.v1\"#\n" +
	"\aNamaste\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"$\n" +
	"\x0eNamasteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\x0fNamasteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2f\n" +
	"\x0eNamasteService\x12T\n" +
	"\aNamaste\x12!.fooapp.namaste.v1.NamasteRequest\x1a\".fooapp.namaste.v1.NamasteResponse(\x010\x01B\xbe\x01\n" +
	"\x15com.fooapp.namaste.v1B\fNamasteProtoP\x01Z1mizu.example/protogen/fooapp/namaste/v1;namastev1\xa2\x02\x03FNX\xaa\x02\x11Fooapp.Namaste.V1\xca\x02\x11Fooapp\\Namaste\\V1\xe2\x02\x1dFooapp\\Namaste\\V1\\GPBMetadata\xea\x02\x13Fooapp::Namaste::V1b\x06proto3"

var (
	file_fooapp_namaste_v1_namaste_proto_rawDescOnce sync.Once
	file_fooapp_namaste_v1_namaste_proto_rawDescData []byte
)

func file_fooapp_namaste_v1_namaste_proto_rawDescGZIP() []byte {
	file_fooapp_namaste_v1_namaste_proto_rawDescOnce.Do(func() {
		file_fooapp_namaste_v1_namaste_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fooapp_namaste_v1_namaste_proto_rawDesc), len(file_fooapp_namaste_v1_namaste_proto_rawDesc)))
	})
	return file_fooapp_namaste_v1_namaste_proto_rawDescData
}

var file_fooapp_namaste_v1_namaste_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_fooapp_namaste_v1_namaste_proto_goTypes = []any{
	(*Namaste)(nil),         // 0: fooapp.namaste.v1.Namaste
	(*NamasteRequest)(nil),  // 1: fooapp.namaste.v1.NamasteRequest
	(*NamasteResponse)(nil), // 2: fooapp.namaste.v1.NamasteResponse
}
var file_fooapp_namaste_v1_namaste_proto_depIdxs = []int32{
	1, // 0: fooapp.namaste.v1.NamasteService.Namaste:input_type -> fooapp.namaste.v1.NamasteRequest
	2, // 1: fooapp.namaste.v1.NamasteService.Namaste:output_type -> fooapp.namaste.v1.NamasteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fooapp_namaste_v1_namaste_proto_init() }
func file_fooapp_namaste_v1_namaste_proto_init() {
	if File_fooapp_namaste_v1_namaste_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fooapp_namaste_v1_namaste_proto_rawDesc), len(file_fooapp_namaste_v1_namaste_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fooapp_namaste_v1_namaste_proto_goTypes,
		DependencyIndexes: file_fooapp_namaste_v1_namaste_proto_depIdxs,
		MessageInfos:      file_fooapp_namaste_v1_namaste_proto_msgTypes,
	}.Build()
	File_fooapp_namaste_v1_namaste_proto = out.File
	file_fooapp_namaste_v1_namaste_proto_goTypes = nil
	file_fooapp_namaste_v1_namaste_proto_depIdxs = nil
}
