// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: app_foo/ciao/v1/ciao.proto

package ciaov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ciao struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ciao) Reset() {
	*x = Ciao{}
	mi := &file_app_foo_ciao_v1_ciao_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ciao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ciao) ProtoMessage() {}

func (x *Ciao) ProtoReflect() protoreflect.Message {
	mi := &file_app_foo_ciao_v1_ciao_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ciao.ProtoReflect.Descriptor instead.
func (*Ciao) Descriptor() ([]byte, []int) {
	return file_app_foo_ciao_v1_ciao_proto_rawDescGZIP(), []int{0}
}

func (x *Ciao) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CiaoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CiaoRequest) Reset() {
	*x = CiaoRequest{}
	mi := &file_app_foo_ciao_v1_ciao_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CiaoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CiaoRequest) ProtoMessage() {}

func (x *CiaoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_foo_ciao_v1_ciao_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CiaoRequest.ProtoReflect.Descriptor instead.
func (*CiaoRequest) Descriptor() ([]byte, []int) {
	return file_app_foo_ciao_v1_ciao_proto_rawDescGZIP(), []int{1}
}

func (x *CiaoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CiaoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CiaoResponse) Reset() {
	*x = CiaoResponse{}
	mi := &file_app_foo_ciao_v1_ciao_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CiaoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CiaoResponse) ProtoMessage() {}

func (x *CiaoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_foo_ciao_v1_ciao_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CiaoResponse.ProtoReflect.Descriptor instead.
func (*CiaoResponse) Descriptor() ([]byte, []int) {
	return file_app_foo_ciao_v1_ciao_proto_rawDescGZIP(), []int{2}
}

func (x *CiaoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_app_foo_ciao_v1_ciao_proto protoreflect.FileDescriptor

const file_app_foo_ciao_v1_ciao_proto_rawDesc = "" +
	"\n" +
	"\x1aapp_foo/ciao/v1/ciao.proto\x12\x0fapp_foo.ciao.v1\" \n" +
	"\x04Ciao\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"!\n" +
	"\vCiaoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\fCiaoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2R\n" +
	"\vCiaoService\x12C\n" +
	"\x04Ciao\x12\x1c.app_foo.ciao.v1.CiaoRequest\x1a\x1d.app_foo.ciao.v1.CiaoResponseB\xa8\x01\n" +
	"\x13com.app_foo.ciao.v1B\tCiaoProtoP\x01Z,mizu.example/protogen/app_foo/ciao/v1;ciaov1\xa2\x02\x03ACX\xaa\x02\x0eAppFoo.Ciao.V1\xca\x02\x0eAppFoo\\Ciao\\V1\xe2\x02\x1aAppFoo\\Ciao\\V1\\GPBMetadata\xea\x02\x10AppFoo::Ciao::V1b\x06proto3"

var (
	file_app_foo_ciao_v1_ciao_proto_rawDescOnce sync.Once
	file_app_foo_ciao_v1_ciao_proto_rawDescData []byte
)

func file_app_foo_ciao_v1_ciao_proto_rawDescGZIP() []byte {
	file_app_foo_ciao_v1_ciao_proto_rawDescOnce.Do(func() {
		file_app_foo_ciao_v1_ciao_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_foo_ciao_v1_ciao_proto_rawDesc), len(file_app_foo_ciao_v1_ciao_proto_rawDesc)))
	})
	return file_app_foo_ciao_v1_ciao_proto_rawDescData
}

var file_app_foo_ciao_v1_ciao_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_foo_ciao_v1_ciao_proto_goTypes = []any{
	(*Ciao)(nil),         // 0: app_foo.ciao.v1.Ciao
	(*CiaoRequest)(nil),  // 1: app_foo.ciao.v1.CiaoRequest
	(*CiaoResponse)(nil), // 2: app_foo.ciao.v1.CiaoResponse
}
var file_app_foo_ciao_v1_ciao_proto_depIdxs = []int32{
	1, // 0: app_foo.ciao.v1.CiaoService.Ciao:input_type -> app_foo.ciao.v1.CiaoRequest
	2, // 1: app_foo.ciao.v1.CiaoService.Ciao:output_type -> app_foo.ciao.v1.CiaoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_foo_ciao_v1_ciao_proto_init() }
func file_app_foo_ciao_v1_ciao_proto_init() {
	if File_app_foo_ciao_v1_ciao_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_foo_ciao_v1_ciao_proto_rawDesc), len(file_app_foo_ciao_v1_ciao_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_foo_ciao_v1_ciao_proto_goTypes,
		DependencyIndexes: file_app_foo_ciao_v1_ciao_proto_depIdxs,
		MessageInfos:      file_app_foo_ciao_v1_ciao_proto_msgTypes,
	}.Build()
	File_app_foo_ciao_v1_ciao_proto = out.File
	file_app_foo_ciao_v1_ciao_proto_goTypes = nil
	file_app_foo_ciao_v1_ciao_proto_depIdxs = nil
}
